steps:  
  - name: "bhgedigital/envsubst"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        /usr/bin/envsubst < .env.production.tmp > .env.production

  # Verify
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat .env.production
 
    # Install
  - name: "gcr.io/fis-us/docker_node"
    entrypoint: /bin/sh
    args:
      - '-c'
      - 
        npm install

    # Test
  - name: "gcr.io/fis-us/docker_node"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        docker run -d -p 6379:6379 redis:6.0.9-alpine
        npm test

  # docker build and push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        docker build -t gcr.io/fis-us/messenger-$BRANCH:$SHORT_SHA .
        docker push gcr.io/fis-us/messenger-$BRANCH:$SHORT_SHA

timeout: 600s