steps:
  - name: "emergyadigital/alpine-node-build"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        if [ $BRANCH_NAME = "main" ]; then
          echo 6377 >> redis_port.txt;
        elif [ $BRANCH_NAME = "release" ]; then
          echo 6378 >> redis_port.txt;
        else
          echo 6376 >> redis_port.txt;
        fi
  
  - name: "bhgedigital/envsubst"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        redis_port=$(cat redis_port.txt)
        export REDIS_PORT=$redis_port

        /usr/bin/envsubst < .env.production.tmp > .env.production
    env:
      - "REDIS_PASSWORD=$_REDIS_PASSWORD"

  # Verify
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat .env.production
 
  # Install
  - name: node
    entrypoint: npm
    args: ['install']

  # # Test
  # - name: node
  #   entrypoint: npm
  #   args: ['test']

  # Verify
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        rm -r node_modules

  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--no-stop-previous-version', '--version=messenger-${BRANCH_NAME}']

timeout: 600s