apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: app
spec:
  rules:
  #MESSENGER
  - host: "messenger.fafago-dev.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: messenger-develop
          servicePort: 8080
  - host: "messenger.fafago-pre.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: messenger-release
          servicePort: 8080
  - host: "messenger.fafago-pro.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: messenger-main
          servicePort: 8080
  #AUTH
  - host: "auth.fafago-dev.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: auth-develop
          servicePort: 80
  - host: "auth.fafago-pre.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: auth-release
          servicePort: 80
  - host: "auth.fafago-pro.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: auth-main
          servicePort: 80
  #PRODUCTS
  - host: "products.fafago-dev.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: products-develop
          servicePort: 8080
  - host: "products.fafago-pre.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: products-release
          servicePort: 8080
  - host: "products.fafago-pro.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: products-main
          servicePort: 8080
  #REVIEWS
  - host: "reviews.fafago-dev.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: reviews-develop
          servicePort: 80
  - host: "reviews.fafago-pre.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: reviews-release
          servicePort: 80
  - host: "reviews.fafago-pro.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: reviews-main
          servicePort: 80
  #FRONTEND
  - host: "frontend.fafago-dev.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend-develop
          servicePort: 8080
  - host: "frontend.fafago-pre.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend-release
          servicePort: 8080
  - host: "frontend.fafago-pro.alexgd.es"
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend-main
          servicePort: 8080
